services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI (guest / guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth_service:
    build: ./auth_service
    container_name: auth_service
    env_file: ./auth_service/.env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  bot:
    build: ./bot_service
    container_name: bot
    env_file: ./bot_service/.env
    command: python -m app.bot.runner
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: ./bot_service
    container_name: worker
    env_file: ./bot_service/.env
    command: celery -A app.infra.celery_app:celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bot_api:
    build: ./bot_service
    container_name: bot_api
    env_file: ./bot_service/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
